export const JOURNEYS_REQUEST = 'JOURNEYS_REQUEST';
export const JOURNEYS_REQUEST_SUCCESS = 'JOURNEYS_REQUEST_SUCCESS';
export const JOURNEYS_REQUEST_FAILD = 'JOURNEYS_REQUEST_FAILD';

export const GET_TIME = 'GET_TIME';
export const START_TIME = 'START_TIME';
export const STOP_TIME = 'STOP_TIME';
